include:
  - project: 'cmr-surgical/customer-operations/analytics-and-tools/tools/gitlab-ci-pipeline'
    ref: latest
    file: '/templates/python-poetry-package-versioned.ci.yml'

variables:
  PUBLISH_TO_PYPI: 'YES'
